import type { PresetPack } from "../types";

export const institutions: PresetPack["institutions"] = [
  // Brokers
  {
    key: "ibkr",
    name: "Interactive Brokers",
    kind: "broker",
    country: "US",
    website: "https://www.interactivebrokers.com",
    ingestMethods: ["api", "csv", "statement_ocr"],
    apiAdapter: "ibkr_flex",
    extractionHints:
      "Activity statements group positions by asset class and currency. Use the 'Open Positions' and 'Cash Report' sections; ignore 'Total' rows.",
  },
  {
    key: "moomoo",
    name: "moomoo",
    kind: "broker",
    country: "SG",
    website: "https://www.moomoo.com/sg",
    ingestMethods: ["api", "statement_ocr"],
    apiAdapter: "moomoo_opend",
    extractionHints:
      "Monthly statements list holdings per market (US, HK, SG). Quantities and prices are in the market's currency.",
  },
  {
    key: "longbridge",
    name: "Longbridge",
    kind: "broker",
    country: "SG",
    website: "https://longbridge.com/sg",
    ingestMethods: ["api", "statement_ocr"],
    apiAdapter: "longbridge",
  },
  {
    key: "poems",
    name: "POEMS (Phillip Securities)",
    kind: "broker",
    country: "SG",
    website: "https://www.poems.com.sg",
    ingestMethods: ["statement_ocr"],
    extractionHints:
      "Statements may contain separate sections for Cash Plus, Custodian and CDP-linked holdings. SGX counters may be shown by name only; include the SGX code when printed.",
  },
  {
    key: "tiger",
    name: "Tiger Brokers",
    kind: "broker",
    country: "SG",
    website: "https://www.tigerbrokers.com.sg",
  },
  {
    key: "webull",
    name: "Webull",
    kind: "broker",
    country: "SG",
    website: "https://www.webull.com.sg",
  },
  {
    key: "saxo",
    name: "Saxo Markets",
    kind: "broker",
    country: "SG",
    website: "https://www.home.saxo/en-sg",
  },
  {
    key: "usmart",
    name: "uSMART",
    kind: "broker",
    country: "SG",
    website: "https://www.usmart.sg",
  },
  {
    key: "fsmone",
    name: "FSMOne",
    kind: "broker",
    country: "SG",
    website: "https://secure.fundsupermart.com",
  },
  { key: "dbs_vickers", name: "DBS Vickers", kind: "broker", country: "SG" },
  {
    key: "ocbc_securities",
    name: "OCBC Securities",
    kind: "broker",
    country: "SG",
  },
  { key: "uob_kay_hian", name: "UOB Kay Hian", kind: "broker", country: "SG" },
  {
    key: "maybank_securities",
    name: "Maybank Securities",
    kind: "broker",
    country: "SG",
  },
  {
    key: "cgs_international",
    name: "CGS International",
    kind: "broker",
    country: "SG",
  },
  {
    key: "syfe",
    name: "Syfe",
    kind: "broker",
    country: "SG",
    website: "https://www.syfe.com",
  },
  {
    key: "endowus",
    name: "Endowus",
    kind: "broker",
    country: "SG",
    website: "https://endowus.com",
  },
  {
    key: "stashaway",
    name: "StashAway",
    kind: "broker",
    country: "SG",
    website: "https://www.stashaway.sg",
  },
  { key: "schwab", name: "Charles Schwab", kind: "broker", country: "US" },
  { key: "fidelity", name: "Fidelity", kind: "broker", country: "US" },
  {
    key: "cdp",
    name: "SGX CDP",
    kind: "depository",
    country: "SG",
    website: "https://www.sgx.com/cdp",
    extractionHints:
      "CDP statements list SGX securities held directly in the user's name. Use the security code (e.g. D05) as the symbol, exchange XSES.",
  },

  // Banks
  {
    key: "dbs",
    name: "DBS Bank",
    kind: "bank",
    country: "SG",
    website: "https://www.dbs.com.sg",
  },
  {
    key: "posb",
    name: "POSB",
    kind: "bank",
    country: "SG",
    website: "https://www.posb.com.sg",
  },
  {
    key: "ocbc",
    name: "OCBC Bank",
    kind: "bank",
    country: "SG",
    website: "https://www.ocbc.com",
  },
  {
    key: "uob",
    name: "UOB",
    kind: "bank",
    country: "SG",
    website: "https://www.uob.com.sg",
  },
  {
    key: "citibank_sg",
    name: "Citibank Singapore",
    kind: "bank",
    country: "SG",
  },
  { key: "hsbc_sg", name: "HSBC Singapore", kind: "bank", country: "SG" },
  {
    key: "standard_chartered_sg",
    name: "Standard Chartered Singapore",
    kind: "bank",
    country: "SG",
  },
  { key: "maybank_sg", name: "Maybank Singapore", kind: "bank", country: "SG" },
  {
    key: "boc_sg",
    name: "Bank of China Singapore",
    kind: "bank",
    country: "SG",
  },
  {
    key: "trust",
    name: "Trust Bank",
    kind: "bank",
    country: "SG",
    website: "https://trustbank.sg",
  },
  {
    key: "gxs",
    name: "GXS Bank",
    kind: "bank",
    country: "SG",
    website: "https://www.gxs.com.sg",
  },
  {
    key: "maribank",
    name: "MariBank",
    kind: "bank",
    country: "SG",
    website: "https://www.maribank.sg",
  },
  { key: "revolut", name: "Revolut", kind: "bank", country: "GB" },
  { key: "wise", name: "Wise", kind: "bank", country: "GB" },
  { key: "youtrip", name: "YouTrip", kind: "card_issuer", country: "SG" },
  {
    key: "amex_sg",
    name: "American Express Singapore",
    kind: "card_issuer",
    country: "SG",
  },

  // Crypto
  { key: "coinbase", name: "Coinbase", kind: "crypto_exchange", country: "US" },
  { key: "binance", name: "Binance", kind: "crypto_exchange" },
  { key: "coinhako", name: "Coinhako", kind: "crypto_exchange", country: "SG" },
  { key: "gemini", name: "Gemini", kind: "crypto_exchange", country: "US" },
];
